apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-app
  labels:
    app: expense-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-app
  template:
    metadata:
      labels:
        app: expense-app
    spec:
      containers:
      - name: expense-app
        image: prashanthkumarbs/tracker:v1
        ports:
        - containerPort: 80