apiVersion: v1
kind: Service
metadata:
  name: expense-app-service
spec:
  selector:
    app: expense-app
  type: Nodeport
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodeport:30080


